Enhancement/edc refactoring (#4)
* refactor dependencies

- update SPDX-FileCopyrightText header
- switch from mkdocs to zensical
- update dependencies (python, github actions)
- use uv
- switch from safety to pip-audit

* pin dependencies

* fix markdownlint version

* refactoring next part

* SPDX-FileCopyrightText

* use uv in README

* fix ci env var

* fix linter

* update dependabot for only security

---------

Co-authored-by: HeinrichAD <HeinrichAD@users.noreply.github.com>

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -1,8 +1,6 @@
 #!/bin/bash
 
-# SPDX-FileCopyrightText: 2024 Benedikt Franke <benedikt.franke@dlr.de>
-# SPDX-FileCopyrightText: 2024 Florian Heinrich <florian.heinrich@dlr.de>
-#
+# SPDX-FileCopyrightText: 2026 German Aerospace Center (DLR)
 # SPDX-License-Identifier: Apache-2.0
 
 ###############################################################################
@@ -69,8 +67,11 @@ function version() {
 
 function versions() {
   info "versions"
-  info "$(python --version)"
-  info "$(python -m pip --version)"
+  if ! command -v docker > /dev/null 2>&1; then
+    warn "uv not found, skipping uv version"
+  else
+    info "uv version: $(uv --version)"
+  fi
   if ! command -v npm > /dev/null 2>&1; then
     warn "npm not found, skipping npm version"
   else
@@ -83,22 +84,16 @@ function versions() {
 
 function install() {
   versions
+  if ! command -v uv &> /dev/null; then
+    if ! command -v curl &> /dev/null; then
+      error "uv and curl are not installed. Please install one of them."
+      exit 1
+    fi
+    info "install uv"
+    curl -LsSf https://astral.sh/uv/install.sh | sh
+  fi
   info "install package"
-  if [ "$#" -eq "0" ]; then
-    python -m pip install -e .
-  else
-    python -m pip install "$@"
-  fi
-  info "install markdown linter"
-  if command -v npm > /dev/null 2>&1; then
-    npm install --no-save markdownlint-cli2
-  else
-    warn "npm not found, skipping markdownlint-cli2 installation"
-  fi
-  info "post-install"
-  py_pack_dir="$(python -c 'import site; print(site.getsitepackages()[0])')"
-  info " + setup user documentation plugins"
-  cp "$py_pack_dir/plantuml_markdown/plantuml_markdown.py" "$py_pack_dir/markdown/extensions/"
+  uv sync --all-extras
 }
 
 function clean() {
@@ -131,58 +126,42 @@ function lint-doc() {
   info "lint documentation"
   # use markdownlint from David Anson (based on nodejs)
   # https://github.com/DavidAnson/markdownlint
-  npm exec markdownlint-cli2 "${DOC_ROOT}/**/*.md" "${PROJECT_ROOT}/README.md"
+  npm exec "markdownlint-cli2@0.22.0" -- "${DOC_ROOT}/**/*.md" "${PROJECT_ROOT}/README.md"
 }
 
 function lint-scripts() {
   info "lint bash scripts"
-  info "shellcheck $(shellcheck --version | head -n 2 | tail -n 1)"
-  shellcheck --external-sources --shell bash --source-path "${PROJECT_ROOT}" "${PROJECT_ROOT}/dev"
-  shellcheck --external-sources --shell bash --source-path "${SCRIPTS_ROOT}" "${SCRIPTS_ROOT}/"*.sh
+  info "shellcheck $(uv run shellcheck --version | head -n 2 | tail -n 1)"
+  uv run shellcheck --external-sources --shell bash --source-path "${PROJECT_ROOT}" "${PROJECT_ROOT}/dev"
+  uv run shellcheck --external-sources --shell bash --source-path "${SCRIPTS_ROOT}" "${SCRIPTS_ROOT}/"*.sh
 }
 
 function doc() {
   versions
-  mkdocs_version="$(python -m mkdocs --version)"
-  info "${mkdocs_version#"python -m "}"
+  info "zensical version: $(uv run zensical --version)"
   info "start documentation server"
-  # check if the user has passed the --dirtyreload flag
-  dirty_flag=false
-  for value in "$@"; do
-    [[ "--dirty" = "$value" ]] && dirty_flag=true
-  done
-  if [[ "$dirty_flag" == "false" ]]; then
-    warn "consider using --dirty to reload only file changes instead of the"
-    warn "whole project. This can lead to a significant speed up during the"
-    warn "documentation development."
-  fi
   # create and serve documentation
-  python -m mkdocs serve "$@"
+  uv run zensical serve "$@"
 }
 
 function doc-build() {
   versions
-  mkdocs_version="$(python -m mkdocs --version)"
-  info "${mkdocs_version#"python -m "}"
+  info "zensical version: $(uv run zensical --version)"
   info "build documentation"
-  python -m mkdocs build "$@"
+  uv run zensical build "$@"
 }
 
 function licenses() {
   info "search for license conflicts"
-  python -m licensecheck
+  uv run licensecheck
   info "search for non-compliant files with REUSE"
-  python -m reuse lint
+  uv run reuse lint
 }
 
 function safety-check() {
   info "check dependencies for known security vulnerabilities"
   # main only no dev dependencies etc.
-  python -m tox --recreate -e safety
-  # alternative
-  #python -m pip install -U safety
-  #safety check
-  ##python -m pip uninstall safety
+  uv run tox --recreate -e safety
 }
 
 
